version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
                commands:
                    - echo install3
            pre_build:
                commands:
                    - echo pre-build3
            build:
                commands:
                    - echo build3
            post_build:
                commands:
                    - echo post-build3